import { expect } from '@playwright/test';
import { test, login } from './support';
for (const role of ['admin', 'reader']) test(`archive menu navigation, language and logout: ${role}`, async ({ page }, info) => {
  await login(page, `fixture-${role}`);
  await expect(page.locator('.archive-navigation [data-view]')).toHaveCount(2);
  await expect(page.locator('.archive-navigation [data-view="sources"], .archive-navigation [data-view="admin"]')).toHaveCount(0);
  const menu = page.locator('.archive-menu'), toggle = menu.locator('summary');
  await toggle.click();
  await expect(menu.locator('[data-view="sources"]')).toHaveText('Quellen und Dokumente');
  await expect(menu.locator('[data-view="admin"]')).toHaveCount(role === 'admin' ? 1 : 0);
  await expect(menu.locator('[data-language]')).toHaveCount(0);
  await expect(menu.locator('.menu-row > svg:first-child')).toHaveCount(role === 'admin' ? 5 : 4);
  await page.screenshot({ path: info.outputPath('menu-uniform.png') });
  await menu.locator('[data-language-menu]').click();
  await expect(menu.locator('[data-language="de"]')).toHaveAttribute('aria-pressed', 'true');
  await expect(menu.locator('[data-language="pt"]')).toHaveAttribute('aria-pressed', 'false');
  await page.keyboard.press('Escape');
  await expect(menu.locator('[data-language-menu]')).toBeFocused();
  await page.keyboard.press('Escape');
  await expect(menu).not.toHaveAttribute('open'); await expect(toggle).toBeFocused();
  await toggle.click(); await menu.locator('[data-language-menu]').click(); await page.locator('[data-language="pt"]').click();
  await expect(menu).not.toHaveAttribute('open');
  await page.locator('.archive-navigation [data-view="chronicle"]').click();
  await expect(page.locator('.chronicle-langs, [data-chronicle-lang]')).toHaveCount(0);
  await page.locator('.chronicle-toc [data-chapter="intro.pt.md"]').click();
  await expect(page.getByRole('heading', { name: 'História de teste', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'História de teste', exact: true })).toBeVisible();
  await toggle.click(); await menu.locator('[data-language-menu]').click(); await page.locator('[data-language="de"]').click();
  await expect(page.getByRole('heading', { name: 'Testgeschichte', exact: true })).toBeVisible();
  await toggle.click(); await menu.locator('[data-view="sources"]').click();
  await expect(page.locator('#sourcesSearch')).toBeVisible();
  await expect(menu).not.toHaveAttribute('open');
  await toggle.click();
  await page.screenshot({ path: info.outputPath('archive-menu.png') });
  expect(await menu.locator('.archive-menu-panel').evaluate(e => { const r = e.getBoundingClientRect(); return r.left >= 0 && r.right <= innerWidth; })).toBe(true);
  await page.locator('#sourcesSearch').click(); await expect(menu).not.toHaveAttribute('open');
  if (role === 'admin') {
    await toggle.click(); await menu.locator('[data-view="admin"]').click();
    await expect(page.locator('#treeSelect')).toBeVisible();
    await expect(menu).not.toHaveAttribute('open');
  }
  await page.locator('.archive-navigation [data-view="chronicle"]').click();
  await page.locator('.chronicle-toc [data-chapter="intro.md"]').click();
  await expect(page.getByRole('heading', { name: 'Testgeschichte', exact: true })).toBeVisible();
  await toggle.click();
  page.once('dialog', dialog => dialog.dismiss());
  await menu.getByRole('button', { name: 'Abmelden', exact: true }).click();
  await expect(menu).not.toHaveAttribute('open');
  await toggle.click(); page.once('dialog', dialog => dialog.accept());
  await menu.getByRole('button', { name: 'Abmelden', exact: true }).click();
  await expect(page.locator('#password')).toBeVisible();
});
