import { expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { test, login } from './support';
test('bilingual editor persists both versions, displays fallback and exports active GEDCOM language',async({page},info)=>{
  await login(page);
  await page.goto('/?person=person_a&action=edit');
  await page.locator('#editor-language-tab-de').click();
  await page.locator('[name="occupation"]').fill('Lehrerin');
  await page.locator('#editor-language-tab-pt').click();
  await page.locator('[name="occupation_pt"]').fill('Professora');
  await page.locator('#editor-language-tab-de').click();
  await page.locator('[name="notes"]').fill('Deutsche Testnotiz.\nZweite deutsche Notiz.');
  await page.locator('#editor-language-tab-pt').click();
  await page.locator('[name="notes_pt"]').fill('Nota de teste em português.');
  await page.locator('#personEditor button[type="submit"]').click();
  await page.goto('/?person=person_a&action=person&language=pt');
  await expect(page.locator('#personDialog')).toContainText('Professora');
  await expect(page.locator('.person-stories')).toContainText('Nota de teste em português.');
  await expect(page.locator('.person-stories')).not.toContainText('Deutsche Testnotiz.');
  await page.goto('/?person=person_a&action=family&language=pt');
  await expect(page.locator('[data-family-person="person_a"] .person-occupation')).toHaveCount(0);
  await page.goto('/?person=person_a&action=edit&language=pt');
  await expect(page.locator('[name="occupation"]')).toHaveValue('Lehrerin');
  await expect(page.locator('[name="notes_pt"]')).toHaveValue('Nota de teste em português.');
  await page.screenshot({path:info.outputPath('bilingual-editor.png')});
  await page.locator('#editor-language-tab-pt').click();
  await page.locator('[name="notes_pt"]').fill('');
  await page.locator('#personEditor button[type="submit"]').click();
  await page.goto('/?person=person_a&action=person&language=pt');
  await expect(page.locator('.person-stories')).toContainText('Zweite deutsche Notiz.');
  await expect(page.locator('#personDialog')).toContainText('Professora');
  for(const language of ['pt','de']) {
    await page.goto(`/?view=admin&language=${language}`);
    page.once('dialog',dialog=>dialog.accept());
    const download=page.waitForEvent('download');
    await page.locator('#exportGedcomBtn').click();
    const file=await download;const ged=await readFile((await file.path())!,'utf8');
    expect(ged).toContain(`1 OCCU ${language==='pt'?'Professora':'Lehrerin'}`);
    expect(ged).not.toContain(language==='pt'?'Lehrerin':'Professora');
    expect(ged).toContain('1 NOTE Deutsche Testnotiz.');
  }
  const draft=await page.evaluate(()=>JSON.parse(localStorage.getItem('familyTreeDraft:demo')!));
  expect(draft.people.person_a).toMatchObject({occupation:'Lehrerin',occupation_pt:'Professora',notes:['Deutsche Testnotiz.','Zweite deutsche Notiz.']});
  expect(draft.people.person_a.notes_pt).toBeUndefined();
  await page.goto('/?person=person_a&action=edit');
  await page.locator('#editor-language-tab-pt').click();
  await page.locator('[name="notes_pt"]').fill('Nota de teste em português.');
  await page.locator('#personEditor button[type="submit"]').click();
  await page.goto('/?view=admin');
  const saving=page.waitForResponse(r=>r.url().endsWith('/save-family'));
  page.once('dialog',dialog=>dialog.accept());
  await page.locator('#adminSync').click();
  expect((await saving).status()).toBe(200);
  const saved=await (await page.request.get('/data/trees/demo.json')).json();
  expect(saved.people.person_a).toMatchObject({occupation:'Lehrerin',occupation_pt:'Professora',notes_pt:['Nota de teste em português.']});
});
