import fs from 'node:fs/promises';
import path from 'node:path';

// Check authored UI sources. dist/ and public/assets/ui/ are generated by Vite.
const root = process.cwd();
const tokenFile = 'src/tokens.css';
const literal = /#[\da-f]{3,8}\b|\brgba?\s*\(/gi;
async function scan(directory) {
  for (const entry of await fs.readdir(directory, { withFileTypes: true })) {
    const file = path.join(directory, entry.name);
    if (entry.isDirectory()) await scan(file);
    else if (/\.(css|svelte)$/.test(file) && path.relative(root, file) !== tokenFile) {
      const text = await fs.readFile(file, 'utf8');
      for (const match of text.matchAll(literal)) {
        throw new Error(`${path.relative(root, file)}:${text.slice(0, match.index).split('\n').length}: literal colour ${match[0]}; use tokens.css`);
      }
    }
  }
}
await scan(path.join(root, 'src'));
if (await fs.access(path.join(root, 'tests/browser')).then(() => true, () => false)) await scan(path.join(root, 'tests/browser'));
const tokens = Object.fromEntries([... (await fs.readFile(tokenFile, 'utf8')).matchAll(/--([\w-]+):\s*(#[\da-f]{6});/gi)].map(m => [m[1], m[2]]));
function luminance(hex) {
  const channels = hex.slice(1).match(/../g).map(part => parseInt(part, 16) / 255)
    .map(c => c <= .04045 ? c / 12.92 : ((c + .055) / 1.055) ** 2.4);
  return channels[0] * .2126 + channels[1] * .7152 + channels[2] * .0722;
}
function contrast(a, b) {
  const values = [luminance(tokens[a]), luminance(tokens[b])].sort((a, b) => b - a);
  return (values[0] + .05) / (values[1] + .05);
}
for (const background of ['bg', 'surface', 'surface-muted', 'focus-soft']) {
  for (const foreground of ['text', 'text-muted', 'primary']) {
    // Selection surfaces deliberately use normal text, never muted text.
    if (background === 'focus-soft' && foreground === 'text-muted') continue;
    const ratio = contrast(foreground, background);
    if (ratio < 4.5) throw new Error(`${foreground}/${background}: contrast ${ratio.toFixed(2)} < 4.5`);
    console.log(`${foreground}/${background}: ${ratio.toFixed(2)}:1`);
  }
}
const inverse = contrast('primary-contrast', 'primary');
if (inverse < 4.5) throw new Error('Primary button contrast below 4.5');
console.log(`primary-contrast/primary: ${inverse.toFixed(2)}:1`);
console.log('Design check passed: no colour literals outside tokens.css; text contrast ≥ 4.5:1.');
